{{- if .Values.adotCollector.sidecar.enabled }}
# ADOT Collector as a Sidecar for deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adotCollector.sidecar.name }}
  namespace: {{.Release.Namespace}}
  labels:
    name: {{ .Values.adotCollector.sidecar.name }}
    {{- include "adotCollector.daemonSet.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.adotCollector.sidecar.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.adotCollector.sidecar.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.adotCollector.sidecar.name }}
        {{- include "adotCollector.daemonSet.commonLabels" . | indent 8 }}
    spec:
      containers:

        - name: {{ .Values.adotCollector.sidecar.name }}
          image: "{{int .Values.adotCollector.image.awsAccountNumber}}.dkr.ecr.{{.Values.adotCollector.image.region}}.amazonaws.com/{{.Values.adotCollector.image.repository}}:{{.Values.adotCollector.image.tag}}"
          env:
            - name: AWS_REGION
              value: {{ .Values.adotCollector.sidecar.region }}
          imagePullPolicy: {{ .Values.adotCollector.image.sidecarPullPolicy }}
          resources:
            {{- toYaml .Values.adotCollector.sidecar.resources | nindent 12 }}
{{- end }}
